services:
  api:
    ports:
      - 8000:8000
    build: .
    environment:
      DB_HOST: db
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    environment:
      POSTGRES_DB: liine
      POSTGRES_PASSWORD: takehome
      POSTGRES_USER: postgres
    restart: always
    # volumes:
    #   - ./db-data/:/var/lib/postgresql/data
