# Generated by Django 4.1.3 on 2022-11-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_hours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('open_datetime', models.DateTimeField()),
                ('close_datetime', models.DateTimeField()),
            ],
        ),
    ]
